# --- Required options --- #

title-head: NRC Army Help
subheading: Nissan Rogue Club

# Name of author
author: Ivan Chornyi

email: nisan.rogue.club@gmail.com

baseurl: "" # the subpath of your site, e.g. blog
url: "https://armyhelp.nissan-rogue.club" # the base hostname & protocol for your site, e.g. http://example.com

youtube_link: https://www.youtube.com/embed/r7BdPXFOUIA

# --- General options --- #

current:
  title: –ó–±—ñ—Ä –∫–æ—à—Ç—ñ–≤ –¥–ª—è –∑–≤'—è–∑–∫—ñ–≤—Ü—ñ–≤ —Å—Ö—ñ–¥–Ω–æ–≥–æ –Ω–∞–ø—Ä—è–º–∫—É
  description: |-
    –¢—Ä–∏–≤–∞—î –∑–±—ñ—Ä –Ω–∞ –ø–æ—Ç—Ä–µ–±–∏ –∑–≤'—è–∑–∫—ñ–≤—Ü—ñ–≤ –∑—ñ —Å–∫–ª–∞–¥—É –û–£–í –•–∞—Ä–∫—ñ–≤, –ø—ñ–¥ –∫–æ–º–∞–Ω–¥—É–≤–∞–Ω–Ω—è–º —è–∫–æ–≥–æ –∑–Ω–∞—Ö–æ–¥—è—Ç—å—Å—è —Ç–∞–∫—ñ –±—Ä–∏–≥–∞–¥–∏ —Ç–∞ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª–∏, —è–∫: 93 –û–ú–ë–† (–•–æ–ª–æ–¥–Ω–∏–π –Ø—Ä), 95 –û–î–®–ë–†, 3 –û–¢–ë–†, 113–∞ —Ö–∞—Ä—å–∫—ñ–≤—Å—å–∫–æ—Ö –±—Ä–∏–≥–∞–¥–∏ –¢–†–û, –∞—Ä—Ç–∏–ª–µ—Ä—ñ—è, –ü–ü–û —Ç–∞ –±–∞–≥–∞—Ç–æ —ñ–Ω—à–∏—Ö. –î–æ —Å–∫–ª–∞–¥—É –≤—ñ–π—Å—å–∫–æ–≤–æ—ó —á–∞—Å—Ç–∏–Ω–∏ –ê1314 (–≤–ª–∞—Å–Ω–µ —É–ø—Ä–∞–≤–ª—ñ–Ω–Ω—è –¥–∞–Ω–∏–º –û–£–í) –≤—Ö–æ–¥–∏—Ç—å –ø–æ—á–µ—Å–Ω–∏–π —É—á–∞—Å–Ω–∏–∫ –Ω–∞—à–æ–≥–æ –∫–ª—É–±—É –°–µ—Ä–≥—ñ–π. –ù–∞–∂–∞–ª—å, –≤—ñ–π–Ω–∞ –Ω—ñ–∫—É–¥–∏ –Ω–µ –ø–æ–¥—ñ–ª–∞—Å—å —ñ –≤–æ—Ä–æ–≥ –Ω–µ –∑—É–ø–∏–Ω—è—î—Ç—å—Å—è.
    <br>
    –¢–∏–º —á–∞—Å–æ–º –°–µ—Ä–≥—ñ–π —ñ –π–æ–≥–æ —Ö–ª–æ–ø—Ü—ñ –Ω–µ–≤–ø–∏–Ω–Ω–æ 24/7 –ø—Ä–∞—Ü—é—é—Ç—å –Ω–∞–¥ —Ç–∏–º —â–æ–± –ª—ñ–Ω—ñ—è —Ñ—Ä–æ–Ω—Ç—É –±—É–ª–∞ –∑–∞–±–µ–∑–ø–µ—á–µ–Ω–∞ —è–∫—ñ—Å–Ω–∏–º, –∑–∞—Ö–∏—â–µ–Ω–Ω–∏–º, –∞ –Ω–∞–π–≥–æ–ª–æ–≤–Ω—ñ—à–µ - –±–µ–∑–ø–µ—Ä–µ–±—ñ–π–Ω–∏–º –∑–≤'—è–∑–∫–æ–º. –ó–≤'—è–∑–æ–∫ —î –¥—É–∂–µ –∫—Ä–∏—Ç–∏—á–Ω–∏–º –¥–ª—è –∫–æ–∂–Ω–æ–≥–æ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—É –ó–°–£ –≤—ñ–¥ —Ä–æ–∑–≤—ñ–¥–∫–∏ –¥–æ –∞—Ä—Ç–∏–ª–µ—Ä—ñ—ó, –≤—ñ–¥ –ø—ñ—Ö–æ—Ç–∏ –¥–æ –ü–ü–û. –°–∞–º–µ –∑–∞–≤–¥—è–∫–∏ –±–µ–∑–ø–µ—Ä–µ–±—ñ–π–Ω–æ–º—É –∑–≤'—è–∑–∫—É –∞—Ä—Ç–∞ –º–æ–∂–µ –æ—Ç—Ä–∏–º–∞—Ç–∏ –∫–æ–æ—Ä–¥–∏–Ω–∞—Ç–∏ —Ç–∞ –∑—Ä–æ–±–∏—Ç–∏ –ø—Ä–∏—Ü—ñ–ª—å–Ω–∏–π –ø–æ—Å—Ç—Ä—ñ–ª, –∑–∞—Å–æ–±–∏ –ü–ü–û –º–æ–∂—É—Ç—å —Å–≤–æ—î—á–∞—Å–Ω–æ –≤—ñ–¥—Å—Ç–µ–∂–∏—Ç–∏ –≤–æ—Ä–æ–∂—ñ —Ä–∞–∫–µ—Ç–∏ —Ç–∞ –∑–Ω–µ—à–∫–æ–¥–∏—Ç–∏ —ó—Ö —Ç–∞ –Ω–µ –∑–Ω–µ—à–∫–æ–¥–∏—Ç–∏ –Ω–∞—à—ñ –ª—ñ—Ç–∞–∫–∏.
    <br>
    –ù–∞—Ä–∞–∑—ñ —î –¥—É–∂–µ –≤–µ–ª–∏–∫–∞ –ø–æ—Ç—Ä–µ–±–∞ –≤ —Ñ—ñ–Ω–∞–Ω—Å—É–≤–∞–Ω–Ω—ñ –Ω–∞ –∑–∞–∫—É–ø—ñ–≤–ª—é –∞–≥—Ä–µ–≥–∞—Ç—ñ–≤, –∫–∞–±–µ–ª—ñ–≤ –∂–∏–≤–ª–µ–Ω–Ω—è, –∫–∞–±–µ–ª—ñ–≤ –ø–µ—Ä–µ–¥–∞—á—ñ –¥–∞–Ω–∏—Ö, —Ç–∞ –±–µ–∑–ª—ñ—á –≤—Å—ñ–ª—è–∫–æ–≥–æ —ñ–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç—É.
    <br>
    –¶—å–æ–≥–æ —Ä–∞–∑—É —Ö–ª–æ–ø—Ü—ñ –Ω–∞–¥—ñ—Å–ª–∞–ª–∏ –Ω–∞–º —Ç—Ä–æ—Ö–∏ —Ü—ñ–∫–∞–≤–∏—Ö –Ω—ñ—à—Ç—è–∫—ñ–≤, —è–∫—ñ –±—É–¥—É—Ç—å —Ä–æ–∑—ñ–≥—Ä–∞–Ω—ñ —Å–µ—Ä–µ–¥ —É—Å—ñ—Ö –¥–æ–Ω–∞—Ç–µ—Ä—ñ–≤:
    <ul>
      <li>
        –∞–Ω–∞–ª–æ–ì–æ–≤–Ω—î—Ç —É–Ω—ñ–∫–∞–ª—å–Ω–∏–π –æ—Ä–æ—á–∏–π –∫–æ–º—É–Ω—ñ–∫–∞—Ç–æ—Ä ‚òéÔ∏è (–≤—ñ–Ω –ø–æ–∑–±–∞–≤–ª–µ–Ω –º–æ–∂–ª–∏–≤–æ—Å—Ç—ñ –≤–∏–∫–æ–Ω—É–≤–∞—Ç–∏ —Å–≤–æ—ó —Ñ—É–Ω–∫—Ü—ñ—ó –∞–ª–µ –±—É–¥–µ –≥–∞—Ä–Ω–∏–º –Ω–∞–≥–∞–¥—É–≤–∞–Ω–Ω—è–º —â–æ –≤–∏ –∑—Ä–æ–±–∏–ª–∏ –≤–∫–ª–∞–¥ –≤ –Ω–∞—à—É –ø–µ—Ä–µ–º–æ–≥—É)
      </li>
      <li>
        –æ—Ä–æ—á—ñ–π –ø—ñ–¥—Å—É–º–æ–∫ üëù
      </li>
      <li>
        –æ—Ä–æ—á—ñ–π –ø–æ–≥–æ–Ω ‚≠ê
      </li>
    </ul>
    –ü–µ—Ä–µ–º–æ–∂—Ü—ñ–≤ –±—É–¥–µ –æ–≥–æ–ª–æ—à–µ–Ω–æ —É <a target="_blank" href="https://t.me/nissan_rogue_club">—á–∞—Ç—ñ –∫–ª—É–±—É</a>.

description: >- # this means to ignore newlines until "baseurl:"
  24 –ª—é—Ç–æ–≥–æ 2022 —Ä–æ–∫—É ‚Çö–æ—Å—ñ—è —Ä–æ–∑–ø–æ—á–∞–ª–∞ –ø–æ–≤–Ω–æ–º–∞—Å—à—Ç–∞–±–Ω–µ –≤—Ç–æ—Ä–≥–Ω–µ–Ω–Ω—è –Ω–∞ —Å—É–≤–µ—Ä–µ–Ω–Ω—ñ —Ç–µ—Ä–∏—Ç–æ—Ä—ñ—ó –£–∫—Ä–∞—ó–Ω–∏. 
  –ö–æ–∂–Ω–æ–≥–æ –¥–Ω—è —Ä—É–π–Ω—É—é—Ç—å—Å—è –¥–æ–ª—ñ, –¥–æ–º—ñ–≤–∫–∏ —Ç–∞ –∂–∏—Ç—Ç—è —Ü—ñ–≤–∏–ª—å–Ω–∏—Ö, –≥–∏–Ω—É—Ç—å –≥—Ä–æ–º–∞–¥—è–Ω–∏ –£–∫—Ä–∞—ó–Ω–∏. 
  –£—Å–µ —á–µ—Ä–µ–∑ –∫—Ä–∏–≤–∞–≤–æ–≥–æ –¥—ñ–¥–∞ –≤—ñ–π–Ω–∏ –ø—É—Ç—ñ–Ω–∞ —Ç–∞ –π–æ–≥–æ –ø–æ—Å—ñ–ø–∞–∫-‚Çö–∞—à–∏—Å—Ç—ñ–≤. 
  –ú–∏ –Ω–µ –∑–∞–ª–∏—à–∞—î–º–æ—Å—è –æ—Å—Ç–æ—Ä–æ–Ω—å, —á–∞—Å—Ç–∏–Ω–∞ —É—á–∞—Å–Ω–∏–∫—ñ–≤ –∫–ª—É–±–∞ –±–æ—Ä–æ–Ω—è—Ç—å –£–∫—Ä–∞—ó–Ω—É —É –ª–∞–≤–∞—Ö –ó–°–£ —Ç–∞ –¢–†–û, —á–∞—Å—Ç–∏–Ω–∞ –≤–æ–ª–æ–Ω—Ç–µ—Ä—è—Ç—å.
  –ö–æ–∂–µ–Ω –∑ –Ω–∞—Å –∑–Ω–∞—î, —â–æ –£–∫—Ä–∞—ó–Ω–∞ –æ–±–æ–≤'—è–∑–∫–æ–≤–æ –ø–µ—Ä–µ–º–æ–∂–µ. 
  –°–∞–π—Ç —Ä–æ–∑—Ä–æ–±–ª–µ–Ω–∏–π –¥–ª—è —ñ–Ω—Ñ–æ—Ä–º—É–≤–∞–Ω–Ω—è —É—á–∞—Å–Ω–∏–∫—ñ–≤ —Ç–∞ –≤—Å—ñ—Ö –Ω–µ–±–∞–π–¥—É–∂–∏—Ö –ø—Ä–æ —Ç–µ, —è–∫ –≤–æ–Ω–∏ –º–æ–∂—É—Ç—å –¥–æ–ø–æ–º–æ–≥—Ç–∏ —Ç–∞ —è–∫ –∫–ª—É–± –¥–æ–ø–æ–º–∞–≥–∞—î –Ω–∞–±–ª–∏–∂–∞—Ç–∏ –¥–µ–Ω—å –ø–µ—Ä–µ–º–æ–≥–∏.
  –¶–µ –Ω–∞—à–∞ –∑–µ–º–ª—è, —Ü–µ –Ω–∞—à–∞ –∫—Ä–∞—ó–Ω–∞! –°–ª–∞–≤–∞ –£–∫—Ä–∞—ó–Ω—ñ! üá∫üá¶

donate_description: >-
  –ú–∏ –±–µ–∑–ø–µ—Ä–µ—Ä–≤–Ω–æ –≤–µ–¥–µ–º–æ –∑–±—ñ—Ä –∫–æ—à—Ç—ñ–≤ —Ç–∞ –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î–º–æ –Ω–∞—à —Ñ–æ–Ω–¥ –Ω–∞ –¥–æ–ø–æ–º–æ–≥—É –ó–°–£, –¢–†–û —Ç–∞ –≤–æ–ª–æ–Ω—Ç–µ—Ä–∞–º. 
  –ù–∞ —â–æ –≤–∏—Ç—Ä–∞—á–∞—é—Ç—å—Å—è –∫–æ—à—Ç–∏ –º–æ–∂–Ω–∞ –∑–Ω–∞–π—Ç–∏ –≤ —Å–µ–∫—Ü—ñ—ó –Ω–∏–∂—á–µ.

partners_description: >-
  –î–µ—è–∫—ñ –ø–∞—Ä—Ç–Ω–µ—Ä–∏ –∫–ª—É–±—É –∑ –ø—Ä–∏—Ö–æ–¥–æ–º –≤—ñ–π–Ω–∏ —Ç–∞–∫–æ–∂ –Ω–µ –∑–∞–ª–∏—à–∏–ª–∏—Å—è –æ—Å—Ç–æ—Ä–æ–Ω—å —Ç–∞ –¥–æ–ø–æ–º–∞–≥–∞—é—Ç—å —á–∏–º –º–æ–∂—É—Ç—å.
  –ù–∞ —ó—Ö —Å—Ç–æ—Ä—ñ–Ω–∫–∞—Ö –≤–∏ –º–æ–∂–µ—Ç–µ –∑–Ω–∞–π—Ç–∏ –∫–æ–Ω—Ç–∞–∫—Ç–∏ —Ç–∞ —è–∫—É –¥–æ–ø–æ–º–æ–≥—É –≤–æ–Ω–∏ –Ω–∞–¥–∞—é—Ç—å.

team_description: >-
  –ù–∞—à–∞ –∫–æ–º–∞–Ω–¥–∞ - —Ü–µ —É–≤–µ—Å—å –∫–ª—É–±, –∫–æ–∂–µ–Ω —É—á–∞—Å–Ω–∏–∫ —î –Ω–µ–≤—ñ–¥'—î–º–Ω–æ—é —á–∞—Å—Ç–∏–Ω–æ—é –∫–ª—É–±—É.
  –ù–∞–∂–∞–ª—å –≤–∫–∞–∑–∞—Ç–∏ –∫–æ–∂–Ω–æ–≥–æ —Ñ—ñ–∑–∏—á–Ω–æ –Ω–µ–º–æ–∂–ª–∏–≤–æ, –±–∞–≥–∞—Ç–æ —Ö—Ç–æ –ø—Ä–æ—Å–∏—Ç—å –∑–∞–ª–∏—à–∏—Ç–∏—Å—è –Ω–µ–Ω–∞–∑–≤–∞–Ω–∏–º –∞–ª–µ –∫–æ–∂–Ω–∏–π —Ä–æ–±–∏—Ç—å —Å–≤—ñ–π –≤–∫–ª–∞–¥: 
  —Ö—Ç–æ—Å—å –¥–æ–ø–æ–º–∞–≥–∞—î —ñ–∑ –∑–∞–∫—É–ø—ñ–≤–ª—è–º–∏, —Ö—Ç–æ—Å—å –ø—ñ–¥—Ç—Ä–∏–º—É—î –¥–æ–Ω–∞—Ç–∞–º–∏, —Ö—Ç–æ—Å—å —Å–∫—Ä–æ–º–Ω–æ –ø–∏—Ç–∞—î —Å–∫—ñ–ª—å–∫–∏ –Ω–µ –≤–∏—Å—Ç–∞—á–∞—î –¥–æ —Ü—ñ–ª—å–æ–≤–æ—ó —Å—É–º–∏ 
  —Ç–∞ –º–æ–≤—á–∫–∏ –≤—ñ–¥–ø—Ä–∞–≤–ª—è—î –Ω–µ–¥–æ—Å—Ç–∞—é—á—É —Å—É–º—É. –£—Å—ñ —Ä–∞–∑–æ–º –º–∏ –≤–µ–ª–∏–∫–∞ —Å–∏–ª–∞, –º–∏ —É–∫—Ä–∞—ó–Ω—Ü—ñ, –º–∏ –æ–±–æ–≤'—è–∑–∫–æ–≤–æ –ø–µ—Ä–µ–º–æ–∂–µ–º–æ –±–æ –∫–æ–∂–Ω–∞ –∫–æ–ø—ñ–π–∫–∞ –¥–æ–ø–æ–º–∞–≥–∞—î –Ω–∞—à—ñ–º –±—ñ–π—Ü—è–º –±–æ—Ä–æ–Ω–∏—Ç–∏ –Ω–∞—à—É –∑–µ–º–ª—é!


# Excerpt word length - Truncate the excerpt of each post on the blog posts page to the specified number of words
excerpt_length: 50

# The keywords to associate with your website, for SEO purposes
keywords: "Nissan Rogue Club, Ukraine, war, putin"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "assets/img/profile.jpg"
favicon: "assets/img/favicon.ico"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-color: "#EAEAEA"
navbar-text-color: "#404040"
navbar-border-color: "#DDDDDD"
page-color: "#FFFFFF"
text-color: "#404040"
link-color: "#008AFF"
hover-color: "#0085A1"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# --- Web Analytics Section --- #

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# --- Comments and Contact --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# Formspree
#formspree: ""

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%-d %B %Y"

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Kiev"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

font-awesome-link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js
bootstrap-bundle-min: https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js
jquery-min: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js
jquery-easing-min: https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js
